### ISSUE TITLE
1khz PWm signal

### ISSUE THREAD

**Issue by BurakOgutken** [nebrius/raspi-pwm#7]
Hello how can i send 1 khz %40 duty signal continusly with this library ?

![image](https://user-images.githubusercontent.com/52740998/132523761-5be049a4-ff41-4070-b74d-2a33efbd3d2d.png)

**Comment by nebrius** [comment]
The constructor takes in options that allow you to set the frequency, and you set the duty cycle with the `write` method. The README details these options.
